### ISSUE TITLE
New roles in seat not applying to already registered Discourse users.

### ISSUE THREAD

**Issue by ghost** [herpaderpaldent/seat-discourse#8]
If i have users on Discourse registered and in seat create a new role and add a user to that role in SeAT, that new role doesn't sync on Discourse.

Example;

Adam is registered on Discourse in Authenticated group, I create new SeAT role called Capitals and add that person to the role, but discourse isn't updating that user's custom usergroups to reflect that.

**Comment by herpaderpaldent** [comment]
That is correct. Unfortunately i cant listen to eloquent relationship events. 
For once because that would need an extra package and i would need to alter vanilla SeAT, which i cant from within a package. 

Currently Roles are synced on a SSO event. Basically there are three methods to sync the new roles.
1. Ask your friend to log out. He will immediatly get logged back with new SSO session and the new role
2. Wait until the current SSO session expire. You can set the length in discourse. 
3. Manually log your friend out via admin panel. 

Every new SSO session will carry over the atm role ownerships of a user. 

Let me know if this helps you?

Your Herp
